### ISSUE TITLE
A window keeps popping up that says "(Experimental) Name for the New Style"

### ISSUE THREAD

**Issue by mikheys** [Haoming02/sd-webui-boomer#2]
When switching from t2i to i2i and back, a window pops up constantly "(Experimental) Name for the New Style". I hit save, I hit cancel. Nothing works.

**Comment by mikheys** [comment]
![image](https://github.com/Haoming02/sd-webui-boomer/assets/34010273/05556032-4c5a-4041-ab4b-8a3fa488942b)

**Comment by Haoming02** [comment]
Interesting 
That message should only pop up when you click the Save Style button…
Do you see a Save Style button under Generate?

**Comment by mikheys** [comment]
I've already tried changing browsers, nothing helps. My buttons look like this:

![image](https://github.com/Haoming02/sd-webui-boomer/assets/34010273/e5b7d739-309e-45cf-8a9c-153431d21491)

**Comment by mikheys** [comment]
Experimentally found out that it happens because of the extension "Style Editor"
https://github.com/chrisgoringe/Styles-Editor.git

Why can this happen? Is there any way to get them to be friends?

**Comment by Haoming02** [comment]
Should be fixed now. Thanks for reporting the issue.
