### ISSUE TITLE
Deforum / Photopea

### ISSUE THREAD

**Issue by alexbofa** [Haoming02/sd-webui-boomer#3]
Hello, can you change button for [Deforum](https://github.com/deforum-art/sd-webui-deforum) and [Photopea](https://github.com/yankooliveira/sd-webui-photopea-embed)?
Deforum
![Deforum](https://github.com/Haoming02/sd-webui-boomer/assets/58225118/edadfc87-82d1-4742-b3dc-2631cbc154e5)
Photopea (txt2img/img2img)
![Photopea](https://github.com/Haoming02/sd-webui-boomer/assets/58225118/502746a2-aed9-48b2-9605-4767242b505a)

**Comment by Haoming02** [comment]
Sorry, but since those are 3rd party Extensions, I do not plan to support them.

Though, you can right click the buttons to inspect elements, and copy their `id` to the JavaScript to apply the same logics.
