### ISSUE TITLE
Unable to get extra network buttons to load.

### ISSUE THREAD

**Issue by MrKuenning** [Haoming02/sd-webui-boomer#5]
![2024-03-05 09_27_06-Stable Diffusion](https://github.com/Haoming02/sd-webui-boomer/assets/16549268/5192d6f3-28f6-41ea-a92f-c70cfc088186)

I installed the extension. I can add the buttons under the generate button.  But I get an error if I try to replace the tree with the folder buttons.

**Comment by Haoming02** [comment]
That error is related to changing the buttons under the generation results. 
Hmm... Did you perhaps disable one of the `Send to ...` button?

**Comment by Haoming02** [comment]
Should be fixed in the latest commit now

**Comment by MrKuenning** [comment]
Working now.
