### ISSUE TITLE
Broken by latest update.

### ISSUE THREAD

**Issue by Ryuukarasu** [Haoming02/sd-webui-boomer#6]
First off, love the extension and my friend who works with me in SD does as well. Been having issues with the most recent update and now the buttons or changes in the extension won't appear. I receive popup messages saying there are errors with the extension. I've tried a fresh install with only boomer but I receive the same error. Any ideas or is just that I'm asking too soon after the update?

**Comment by Haoming02** [comment]
Hmm... I just tried it and didn't get any error.

Works just fine for `v1.10.1` on my end...

**Comment by Ryuukarasu** [comment]
I've took a screenshot of all the messages. This is a fresh install of SD with no other extensions installed. This only occurred after the recent update.

![Missing Button](https://github.com/user-attachments/assets/235042b0-b19d-4182-bea8-90081fcd1005)
I included this one to show that even with all the messages the changes were not applied to the UI

![Problem 1](https://github.com/user-attachments/assets/d68a98aa-53d8-46e5-abcc-9df75ed3d4ca)
![Problem 2](https://github.com/user-attachments/assets/1aa469bc-b9b6-4737-8360-a13960cd23a3)
![Problem 3](https://github.com/user-attachments/assets/a4ea05a0-d587-47d9-aa57-6327e35420f0)
![Problem 4](https://github.com/user-attachments/assets/3008b557-5580-49ad-af24-69796ea5a56c)
![Problem 5](https://github.com/user-attachments/assets/404cad31-7051-4a0d-8be7-0022b923d620)
![Problem 6](https://github.com/user-attachments/assets/e353a238-856c-453d-8cae-bab03169cc16)

**Comment by Haoming02** [comment]
Are you using `Automatic1111`?

I can't recreate it...

**Comment by Haoming02** [comment]
<p align="center"><img src="https://github.com/user-attachments/assets/da119578-59fc-4475-a743-0c73d69a15d4"></p>

**Comment by pro-krastinator** [comment]
I've faced the same issue. I am using SD Forge. Once I removed the extension, the error pop-up gone.

**Comment by Haoming02** [comment]
> Forge

Thank you. That makes ***a lot of*** difference, as the new Forge is basically completely different

@EPBrassil Please mention that next time to save every body hours of headache

**Comment by Ryuukarasu** [comment]
That's pretty condescending of you to say. I am not using Forge and still having the same issue actually. I'm just gonna forget this issue now due to that comment.

**Comment by Haoming02** [comment]
And I will reopen it cause I still have to fix it

**Comment by Haoming02** [comment]
Also, even til now you still gave **zero** information on what frontend you are actually using.

And so far, I've only managed to recreate the issue, **once**, on the new Forge, among 4 different instances of UIs, across 2 separate PCs each.

**Comment by Haoming02** [comment]
Make it use relative elements instead of hardcoding some of the nodes.

Should work for all UIs now...
